#!/bin/sh

picom -b
xrdb -load $HOME/.Xresources
sxhkd &
feh --no-fehbg --bg-scale "$HOME/repo/archlinux/lancer.jpg"
setxkbmap -model pc105 -layout us,ru -option grp:toggle
xorg-xsetroot -cursor_name left_ptr
$XDG_CONFIG_HOME/polybar/launch.sh

### Gaps ###
bspc config top_padding        2
bspc config bottom_padding     2
bspc config left_padding       2
bspc config right_padding      2
bspc config border_width       2
bspc config window_gap         4

### Focusing behavior ###
bspc config focus_follows_pointer true
bspc config history_aware_focus true
bspc config focus_by_distance true
bspc monitor -d 1 2 3 4 5 6 7 8
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
